on:
  push:
    branches: [ "SCRUM-131-Setting-up-Github-Actions-workflow" ]

jobs:
  # PRVO OPRAVILO: Gradnja in nalaganje slik
  build-and-push:
    # Določimo, da se bo opravilo izvajalo na vm Ubuntu
    runs-on: ubuntu-latest
    
    # Določimo korake, ki se bodo izvedli v tem opravilu
    steps:
      # Korak 1: Prenos kode iz repozitorija na vm
      - name: Prenos kode (Checkout)
        uses: actions/checkout@v4

      # Korak 2: Prijava v Docker Hub z uporabo skrivnosti
      - name: Prijava v Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Korak 3: Gradnja in nalaganje slike za backend
      - name: Zgradi in naloži backend sliko
        uses: docker/build-push-action@v5
        with:
          context: ./backend  # Mapa, kjer je Dockerfile za backend
          push: true          # Povemo, da naj sliko tudi naloži (push)
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/digital-garden-backend:latest # Ime slike

      # Korak 4: Gradnja in nalaganje slike za frontend
      - name: Zgradi in naloži frontend sliko
        uses: docker/build-push-action@v5
        with:
          context: ./frontend # Mapa, kjer je Dockerfile za frontend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/digital-garden-frontend:latest
  #  # DRUGO OPRAVILO: Sprožitev webhooka na Azure strežniku
  # deploy:
  #   # To opravilo je odvisno od prejšnjega.
  #   needs: build-and-push
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Sproži webhook za namestitev
  #       uses: distributhor/webhook@v3
  #       with:
  #         webhook_url: ${{ secrets.WEBHOOK_URL }}
  #         webhook_secret: ${{ secrets.WEBHOOK_SECRET }}